#! /usr/bin/env ruby
#
  ENV['DEPLOY_SCRIPT'] = File.expand_path(__FILE__)
  ENV['RACK_ENV'] ||= 'production'

#
  require 'net/http'
  require 'fileutils'

#
  require_relative '../config/boot.rb'

#
  $debug = ARGV.delete('-d') || ARGV.delete('--debug')
  author = ARGV.shift || 'dojo4@dojo4.com'

  script_dir = File.expand_path(File.dirname(__FILE__))
  mm_root = File.dirname(script_dir)

#
  spawn = proc{|command| system(command) || abort("#{ command } #=> #{ $?.exitstatus }")}

#
  Dir.chdir(mm_root)

#
  spawn["./script/build"]


# this stupid loop combats out-of-memory errors on netlify gem/servers
#
  command     = "bundle exec rake netlify:deploy"

  deployed    = false
  checked     = false
  n           = 3
  netlify_url = Site.config.get(:netlify, :site, :url)
  url         = Site.config.get(:url) || netlify_url

# HACK - work around netlify deployments issues
#
  trap('SIGINT'){ exit!(42) }

  1.times do
    n.times do
      deployed = Bundler.clean_system(command)

      if deployed
        break
      end

      explicative = %w( blargh! dang! doh! ).sort_by{ rand }.first
      Say.say("#{ explicative } deploy blew up, retrying...", :color => :red)
      sleep(rand * 10)
    end

    n.times do
      checked =
        [url, netlify_url].any? do |u|
          begin
            Net::HTTP.get_response(URI(u)).code.to_i == 200
            true
          rescue Object => e
            false
          end
        end

      break if checked

      explicative = %w( blargh! dang! doh! ).sort_by{ rand }.first
      Say.say("#{ explicative } check blew up, retrying...", :color => :red)
      sleep(rand * 10)
    end
  end

#
  exit(deployed && checked ? 0 : 1)
