# If you do not have OpenSSL installed, change
# the following line to use 'http://'
source 'https://rubygems.org'

# For faster file watcher updates on Windows:
# gem 'wdm', '~> 0.1.0', platforms: [:mswin, :mingw]

# Windows does not come with time zone data
# gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]

# Middleman Gems
#gem 'middleman', '>= 4.0.0'
#gem 'middleman-livereload'
#gem 'middleman-compass', '>= 4.0.0'

gem 'middleman', '~> 4.2'
gem 'middleman-autoprefixer', '~> 2.7'

gem "rake"

gem "netlify"
gem "pry"
gem "stringex"
gem "redcarpet"
gem "nokogiri"
gem "rb-pygments"
gem "auto_excerpt"

gem "sekrets"
gem "map"
gem "tagz"


# gem "middleman-dato"
# gem "data"

# uncomment to use ./script/bucket
#gem "main"
#gem "multi_json"
#gem "aws-sdk", "~> 1"
#gem "fattr"
#gem "mime-types"
