identifier: bird
title: Bird
slug: bird
name: abird

description : >-
  Bird's site

keywords:
  - bird
  - meditation

author: DOJO4

development:
  url: http://localhost:4567/

staging:
  url: https://staging-static.com

production:
  url: https://nervous-shaw-3cf314.netlify.com

